In [1]:
import pandas as pd
import numpy as np

In [2]:
Hotel_Reviews=pd.read_csv("Hotel_Reviews.csv")
Hotel_Reviews.head()

,Hotel_Address,Additional_Number_of_Scoring,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,Tags,days_since_review,lat,lng
0,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,8/3/2017,7.7,Hotel Arena,Russia,I am so angry that i made this post available...,397,1403,Only the park outside of the hotel was beauti...,11,7,2.9,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,52.360576,4.915968
1,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,8/3/2017,7.7,Hotel Arena,Ireland,No Negative,0,1403,No real complaints the hotel was great great ...,105,7,7.5,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,52.360576,4.915968
2,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/31/2017,7.7,Hotel Arena,Australia,Rooms are nice but for elderly a bit difficul...,42,1403,Location was good and staff were ok It is cut...,21,9,7.1,"[' Leisure trip ', ' Family with young childre...",3 days,52.360576,4.915968
3,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/31/2017,7.7,Hotel Arena,United Kingdom,My room was dirty and I was afraid to walk ba...,210,1403,Great location in nice surroundings the bar a...,26,1,3.8,"[' Leisure trip ', ' Solo traveler ', ' Duplex...",3 days,52.360576,4.915968
4,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/24/2017,7.7,Hotel Arena,New Zealand,You When I booked with your company on line y...,140,1403,Amazing location and building Romantic setting,8,3,6.7,"[' Leisure trip ', ' Couple ', ' Suite ', ' St...",10 days,52.360576,4.915968

In [3]:
Hotel_Reviews.shape

(515738, 17)

In [6]:
Nationalities=Hotel_Reviews.Reviewer_Nationality.unique()

In [7]:
Nationalities.size

227

In [8]:
Reviewer_Nationality=np.array([])
mean_reviewer_rating=np.array([])
mode_reviewer_rating=np.array([])
std_reviewer_rating=np.array([])
outlier_threshold=np.array([])
inlier_threshold=np.array([])
mean_average_score=np.array([])

In [11]:
for Nationality in Nationalities:
    TEMP=Hotel_Reviews.loc[Hotel_Reviews['Reviewer_Nationality']==Nationality]
    
    Reviewer_Nationality=np.append(Reviewer_Nationality,Nationality)
    
    mean_reviewer_rating=np.append(mean_reviewer_rating,TEMP['Reviewer_Score'].mean())
    mode_reviewer_rating=np.append(mode_reviewer_rating,TEMP['Reviewer_Score'].mode())
    std_reviewer_rating=np.append(std_reviewer_rating,TEMP['Reviewer_Score'].std())
    
    outlier_threshold=np.append(outlier_threshold,TEMP['Reviewer_Score'].mean()+(2*TEMP['Reviewer_Score'].std()))
    inlier_threshold=np.append(inlier_threshold,TEMP['Reviewer_Score'].std())
    
    mean_average_score=np.append(mean_average_score,TEMP['Average_Score'].mean())

In [12]:
columns=['Reviewer_Nationality','mean_reviewer_rating','std_reviewer_rating','outlier_threshold','inlier_threshold','mean_average_score']

In [13]:
data=np.column_stack((Reviewer_Nationality,mean_reviewer_rating,std_reviewer_rating,outlier_threshold,inlier_threshold,mean_average_score))

In [14]:
HotelReviews=pd.DataFrame(data,columns=columns)

In [15]:
HotelReviews

,Reviewer_Nationality,mean_reviewer_rating,std_reviewer_rating,outlier_threshold,inlier_threshold,mean_average_score
0,Russia,8.27779487179478,1.6894340748242014,11.656663021443183,1.6894340748242014,8.47030769230766
1,Ireland,8.464052067175164,1.5538905137015844,11.571833094578333,1.5538905137015844,8.330572604033232
2,Australia,8.591718159181339,1.4840054570363082,11.559729073253955,1.4840054570363082,8.46175873835659
3,United Kingdom,8.486352070988723,1.6092258439198386,11.7048037588284,1.6092258439198386,8.3779140128676
4,New Zealand,8.654834723509321,1.3896421577179987,11.434119038945319,1.3896421577179987,8.422737102255143
5,Poland,8.233414043583467,1.615199453482247,11.463812950547961,1.615199453482247,8.352092701487342
6,Belgium,8.17406731885258,1.607705539767267,11.389478398387116,1.607705539767267,8.430906980600279
7,Norway,8.145321023919378,1.5827583466221669,11.310837717163711,1.5827583466221669,8.357154846831687
8,France,8.14501096491228,1.7444304163836333,11.633871797679546,1.7444304163836333,8.369709429824587
9,Italy,8.114556754988573,1.7260716910216647,11.566700137031903,1.7260716910216647,8.340922473012737
10,Canada,8.547783126425132,1.5226960777952407,11.593175282015615,1.5226960777952407,8.446921712693259
11,Netherlands,8.125148198814527,1.6130924654746006,11.351333129763727,1.6130924654746006,8.398928408572853
12,Germany,8.132477018007844,1.6811495323911292,11.494776082790102,1.6811495323911292,8.364853293036166
13,United States of America,8.786999463836956,1.5121321524176201,11.811263768672196,1.5121321524176201,8.537302819086785
14,Hungary,8.502517162471376,1.494289520189937,11.49109620285125,1.494289520189937,8.37977116704802
15,Israel,8.694447806353883,1.5161563076526596,11.726760421659202,1.5161563076526596,8.501558245083205
16,Switzerland,8.161592532841745,1.6064605646679284,11.374513662177602,1.6064605646679284,8.468299147269047
17,India,7.8824265347686175,1.8434336289764344,11.569293792721487,1.8434336289764344,8.29738143729995
18,United Arab Emirates,7.8788275525160305,1.9069466094709577,11.692720771457946,1.9069466094709577,8.443331704934154
19,Malaysia,8.162559745087616,1.5228564074248114,11.208272559937239,1.5228564074248114,8.290015932023362
20,Denmark,8.07320185614849,1.6829454056488804,11.43909266744625,1.6829454056488804,8.326392111368913
21,South Africa,8.364407223239896,1.628944618855597,11.62229646095109,1.628944618855597,8.411698508243914
22,Rwanda,8.215384615384615,1.8183537214772751,11.852092058339165,1.8183537214772751,8.392307692307693
23,Finland,8.289666484417713,1.4337512381844069,11.157168960786528,1.4337512381844069,8.396555494805893
24,Portugal,8.045296356715614,1.6237151635232958,11.292726683762206,1.6237151635232958,8.364382816748236
25,Luxembourg,8.201766004415035,1.6043698981058006,11.410505800626636,1.6043698981058006,8.436350257542298
26,Spain,8.168693265779988,1.7176023325145713,11.60389793080913,1.7176023325145713,8.354865948912773
27,Malta,8.476439169139482,1.5138345852285238,11.50410833959653,1.5138345852285238,8.267715133531151
28,China,8.44114705882342,1.6330033884314246,11.707153835686269,1.6330033884314246,8.50026470588234
29,Turkey,8.0033798677443,1.8059040195027591,11.615187906749819,1.8059040195027591,8.397759000734728
...,...,...,...,...,...,...
197,Bolivia,8.716666666666669,1.5069447079907,11.730556082648068,1.5069447079907,8.372222222222222
198,Dominica,8.463636363636363,1.981046555370533,12.425729474377428,1.981046555370533,8.536363636363637
199,Niger,9.15,1.2020815280171302,11.55416305603426,1.2020815280171302,8.45
200,Samoa,8.55,1.705872210923198,11.961744421846397,1.705872210923198,8.625
201,Lesotho,7.233333333333333,0.23094010767585052,7.695213548685034,0.23094010767585052,8.466666666666667
202,French Polynesia,7.766666666666666,2.150193789716018,12.067054246098703,2.150193789716018,8.733333333333333
203,Grenada,7.8,1.053565375285274,9.907130750570548,1.053565375285274,7.766666666666667
204,Wallis and Futuna,7.3,3.2526911934581184,13.805382386916236,3.2526911934581184,8.3
205,Svalbard Jan Mayen,10.0,nan,nan,nan,8.8
206,Djibouti,7.9,0.0,7.9,0.0,8.149999999999999
207,Saint Barts,9.033333333333333,1.3428824718989123,11.719098277131158,1.3428824718989123,8.5
208,Kiribati,7.5,0.5656854249492386,8.631370849898477,0.5656854249492386,6.7
209,Cook Islands,7.3,3.2526911934581184,13.805382386916236,3.2526911934581184,8.7
210,Congo,9.166666666666666,0.750555349946513,10.667777366559692,0.750555349946513,8.833333333333334
211,Somalia,8.766666666666666,1.4977761292440648,11.762218925154794,1.4977761292440648,8.466666666666667
212,Eritrea,8.35,1.7677669529663689,11.885533905932737,1.7677669529663689,8.15
213,Saint Vincent Grenadines,8.35,2.3334523779156067,13.016904755831213,2.3334523779156067,7.9
214,San Marino,8.9,1.5716233645501714,12.043246729100343,1.5716233645501714,8.566666666666668
215,Turkmenistan,7.359999999999999,0.870631954387157,9.101263908774314,0.870631954387157,7.919999999999999
216,Vatican City,7.9,nan,nan,nan,8.7
217,South Sudan,9.2,0.0,9.2,0.0,8.100000000000001
218,Anguilla,7.5,nan,nan,nan,8.5
219,Cocos K I,8.95,0.9192388155425111,10.788477631085021,0.9192388155425111,8.5
220,Bonaire St Eustatius and Saba,9.066666666666666,0.46188021535170004,9.990427097370066,0.46188021535170004,8.466666666666667
221,Cape Verde,9.6,nan,nan,nan,9.0
222,Northern Mariana Islands,5.8,nan,nan,nan,7.9
223,Tuvalu,7.1,nan,nan,nan,8.0
224,Guinea,7.5,nan,nan,nan,8.4
225,American Samoa,5.65,1.4849242404917502,8.619848480983501,1.4849242404917502,8.05
226,Palau,8.3,nan,nan,nan,8.1